### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by msimonc** [RishikeshDarandale/serverless-graphql-boilerplate#148]
Everything starts OK, but I get LOOPING when I browse to: http://localhost:3000/graphql :

> Serverless: GET /graphql (λ: graphql)
[offline] requestId: cjycechcf0000p78iahz4cuo3
[offline] contentType: application/json
[offline] requestTemplate: 
[offline] payload: null
[offline] Invalidating cache...
[offline] Loading handler... (/Projects/Serverless/serverless-graphql-boilerplate/.webpack/service/functions/graphql)
[offline] event: { body: null,
  headers: 
   { Host: 'localhost:3000',
     Connection: 'keep-alive',
     'Upgrade-Insecure-Requests': '1',
     'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36',
     Accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
     'Accept-Encoding': 'gzip, deflate, br',
     'Accept-Language': 'en-US,en;q=0.9' },
  httpMethod: 'GET',
  multiValueHeaders: 
   { Host: [ 'localhost:3000' ],
     Connection: [ 'keep-alive' ],
     'Upgrade-Insecure-Requests': [ '1' ],
     'User-Agent': 
      [ 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36' ],
     Accept: 
      [ 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' ],
     'Accept-Encoding': [ 'gzip, deflate, br' ],
     'Accept-Language': [ 'en-US,en;q=0.9' ] },
  multiValueQueryStringParameters: null,
  path: '/graphql',
  pathParameters: null,
  queryStringParameters: null,
  requestContext: 
   { accountId: 'offlineContext_accountId',
     apiId: 'offlineContext_apiId',
     authorizer: 
      { principalId: 'offlineContext_authorizer_principalId',
        claims: undefined },
     httpMethod: 'GET',
     identity: 
      { accountId: 'offlineContext_accountId',
        apiKey: 'offlineContext_apiKey',
        caller: 'offlineContext_caller',
        cognitoAuthenticationProvider: 'offlineContext_cognitoAuthenticationProvider',
        cognitoAuthenticationType: 'offlineContext_cognitoAuthenticationType',
        cognitoIdentityId: 'offlineContext_cognitoIdentityId',
        cognitoIdentityPoolId: 'offlineContext_cognitoIdentityPoolId',
        sourceIp: '127.0.0.1',
        user: 'offlineContext_user',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36',
        userArn: 'offlineContext_userArn' },
     protocol: 'HTTP/1.1',
     requestId: 'offlineContext_requestId_cjycechlg0001p78i5jya84pd',
     requestTimeEpoch: 1563679408328,
     resourceId: 'offlineContext_resourceId',
     resourcePath: '/graphql',
     stage: 'local' },
  resource: '/graphql',
  stageVariables: null,
  isOffline: true }
[offline] _____ CALLING HANDLER _____
[offline] _____ HANDLER RESOLVED _____
[offline] Using response 'default'
[offline] _____ RESPONSE PARAMETERS PROCCESSING _____
[offline] Found 0 responseParameters for 'default' response
[offline] headers { 'Content-Type': [ 'text/html' ],
  'access-control-allow-credentials': [ 'true' ],
  'access-control-allow-origin': [ '*' ] }
[offline] requestId: cjycechcf0000p78iahz4cuo3

**Comment by RishikeshDarandale** [comment]
@msimonc ,
I am able to run it as below:

```
rishikesh$ npx sls offline start --stage local
Serverless: Bundling with Webpack...
Time: 218ms
Built at: 07/22/2019 10:29:15 AM
               Asset      Size             Chunks             Chunk Names
functions/graphql.js  9.51 KiB  functions/graphql  [emitted]  functions/graphql
Entrypoint functions/graphql = functions/graphql.js
[./functions/graphql.js] 736 bytes {functions/graphql} [built]
[./src/graphql sync \.js$] ./src/graphql sync nonrecursive \.js$ 190 bytes {functions/graphql} [built]
[./src/graphql/schema.js] 626 bytes {functions/graphql} [built]
[./src/graphql/type.js] 748 bytes {functions/graphql} [optional] [built]
[./src/libs/utils/LogUtils.js] 335 bytes {functions/graphql} [built]
[apollo-server-lambda] external "apollo-server-lambda" 42 bytes {functions/graphql} [built]
[lambda-log] external "lambda-log" 42 bytes {functions/graphql} [built]
[lodash] external "lodash" 42 bytes {functions/graphql} [built]
Serverless: Watching for changes...
Dynamodb Local Started, Visit: http://localhost:8000/shell
Serverless: DynamoDB - created table local-example-table
Seed running complete for table: local-example-table
Serverless: Starting Offline: local/us-east-1.

Serverless: Routes for graphql:
Serverless: POST /graphql
Serverless: GET /graphql
Serverless: POST /{apiVersion}/functions/local-serverless-graphql-boilerplate-function/invocations

Serverless: Offline [HTTP] listening on http://localhost:3000
Serverless: Enter "rp" to replay the last request

Serverless: GET /graphql (λ: graphql)
```

I am able to browse the playground as well.

![Screenshot from 2019-07-22 10-35-32](https://user-images.githubusercontent.com/4144769/61607528-c4d13080-ac6c-11e9-8528-edd84e7733a0.png)
